import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({

    container: {
        flex: 1,
    },
    mainContent: {
        flex: 1,
    },
    tabContainer: {
        flex: 1,
        height: Dimensions.get('window').height - 150,
        zIndex: 1,
        backgroundColor: 'white',
    },
    tabView: {
        flex: 1,
    },
    tabBar: {
        borderBottomWidth: 0,
        backgroundColor: 'white',
        zIndex: 2,
        height: 45,
    },

    tabItem: {
        alignSelf: 'baseline',
        paddingHorizontal: 10,
        width: 'auto',  
    },
    tabIndicator: {
        backgroundColor: '#5271ff',
        height: 2.5,
    },
    tabLabel: {
        fontSize: 12,
       
        color: '#666',
    },
    headerSection: {
        zIndex: 1000,
        
    },
    searchHeader: {
        paddingHorizontal: 10,
        paddingBottom: 5,
    },
    searchBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    searchBar: {
        flexDirection: 'row',
        backgroundColor: '#f5f5f5',
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 16,
        alignItems: 'center',
        flex: 1,
    },
    searchInput: {
        flex: 1,
        marginLeft: 8,
        fontSize: 14,
        color: '#333',
       
    },
    clearButton: {
        padding: 4,
    },
    cancelButton: {
        paddingRight: 12,
    },
    cancelText: {
        color: '#333',
        fontSize: 14,
       
    },
    gridItem: {
        overflow: 'hidden',
        position: 'relative',
        backgroundColor: '#f0f0f0',
        borderWidth: 0.5,
        borderColor: '#dbdbdb',
    },
    gridImage: {
        width: '100%',
        height: '100%',
    },
    gradientOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.1)',
    },
    contentOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 12,
        backgroundColor: 'rgba(0,0,0,0.4)',
    },
    contentTitle: {
        color: 'white',
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
    },
    engagementRow: {
        flexDirection: 'row',
        gap: 8,
    },
    engagementBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 4,
    },
    engagementText: {
        color: 'white',
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '600',
    },
    videoIndicator: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -20 }, { translateY: -20 }],
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(0,0,0,0.6)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    durationBadge: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.75)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    durationText: {
        color: 'white',
        fontSize: 12,
        fontWeight: '600',
    },
    viewsBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.75)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 4,
    },
    viewsText: {
        color: 'white',
        fontSize: 12,
        fontWeight: '600',
    },
    trendingBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: '#5271ff',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    trendingSection: {
        paddingTop: 24,
        paddingBottom: 20,
        borderBottomWidth: 8,
        borderBottomColor: '#f5f5f5',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    sectionTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#333',
    },
    seeAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
    },
    seeAllText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#333',
    },
    trendingList: {
        paddingLeft: 16,
        paddingRight: 8,
    },
    trendingItemContainer: {
        marginRight: 16,
    },
    trendingItem: {
        width: Dimensions.get('window').width - 80,
        height: 180,
        borderRadius: 16,
        overflow: 'hidden',
        backgroundColor: '#f0f0f0',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.12,
        shadowRadius: 5,
    },
    trendingTopGradient: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 80,
        zIndex: 1,
    },
    trendingRankContainer: {
        position: 'absolute',
        top: 12,
        left: 12,
        zIndex: 10,
        borderRadius: 16,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    trendingRank: {
        color: 'white',
        fontSize: 14,
        fontWeight: '700',
    },
    trendingContent: {
        width: '100%',
        height: '100%',
        position: 'relative',
    },
    trendingImage: {
        width: '100%',
        height: '100%',
    },
    trendingGradient: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    trendingInfo: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 15,
    },
    trendingTitle: {
        color: 'white',
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 8,
        letterSpacing: 0.2,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    trendingStats: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    trendingStat: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    trendingStatText: {
        color: 'white',
        fontSize: 12,
        fontWeight: '500',
    },
    trendingPlayButton: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        width: 50,
        height: 50,
        marginLeft: -25,
        marginTop: -25,
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.6)',
    },
    scrollIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 16,
    },
    scrollIndicatorActive: {
        width: 20,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#5271ff',
    },
    scrollIndicatorDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#DDD',
    },
    trendingCategories: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        marginTop: 20,
        gap: 10,
        flexWrap: 'wrap',
    },
    categoryTag: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: '#f5f5f5',
        marginBottom: 6,
    },
    categoryTagActive: {
        backgroundColor: '#333',
    },
    categoryTagText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#555',
    },
    categoryTagTextActive: {
        fontSize: 14,
        fontWeight: '600',
        color: 'white',
    },
    resultsContainer: {
        flex: 1,
    },
    searchSuggestions: {
        padding: 16,
    },
    suggestionsTitle: {
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 16,
        color: '#333',
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 4,
        borderBottomWidth: 0.5,
        borderBottomColor: '#f5f5f5',
    },
    suggestionText: {
        fontSize: 16,
        marginLeft: 12,
        color: '#333',
        fontWeight: '500',
    },
    emptyContainer: {
        flex: 1,
        height: 400,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    emptyText: {
        fontSize: 22,
        fontWeight: '700',
        color: '#333',
        marginTop: 24,
        textAlign: 'center',
    },
    emptySubtext: {
        fontSize: 16,
        color: '#777',
        marginTop: 12,
        textAlign: 'center',
        lineHeight: 22,
    },
    emptyActionButton: {
        marginTop: 32,
        backgroundColor: '#5271ff',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 24,
        elevation: 2,
        shadowColor: '#5271ff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    emptyActionButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    trendingHeader: {
        padding: 16,
        marginBottom: 8,
    },
    trendingHeaderTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#333',
        marginBottom: 4,
    },
    trendingHeaderSubtitle: {
        fontSize: 16,
        color: '#666',
    },
    gridContainer: {
        flex: 1,
        backgroundColor: 'white',
    },
    trendingViewAllCard: {
        width: 200,
        height: 180,
        borderRadius: 16,
        overflow: 'hidden',
        marginRight: 16,
    },
    trendingViewAllGradient: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    trendingViewAllText: {
        color: 'white',
        fontSize: 18,
        fontWeight: '700',
        marginTop: 12,
        textAlign: 'center',
    },
    trendingViewAllBadge: {
        backgroundColor: 'rgba(255,255,255,0.3)',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 16,
        marginTop: 12,
    },
    trendingViewAllBadgeText: {
        color: 'white',
        fontWeight: '700',
        fontSize: 14,
    },
    mainScrollContent: {
        flexGrow: 1,
        paddingBottom: 100,
    },
    customGridContainer: {
        flex: 1,
        width: '100%',
    },
    gridRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    loadingFooter: {
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
})